---
id: 1022744A-A7A1-46B2-90FD-112B1BF47706
creation-date: 2023-05-02T22:32:18
type: walkthrough
aliases:
  - Python Context Manager
tags:
  - python
  - design-principle
catalogs:
  - c-2023-05-03-23-28
---

## üìñ Use Cases Traits

*Context Manager* is specifically useful when dealing with **programmes that has a strict Entering & Exiting behaviours** (hence Context), and open for modifications within the Context. 

Common for programmes that **need to perform crucial procedures regardless of success/ failure**: 

- resources management - discard resources whenever finish
- connection management - disconnect to server/ database whenever finish
- files management - close files whenever finish

It is also useful as a "**fallback procedure**" to handle certain Exceptions, e.g., 
- rollback files/ databases when facing errors
- returning `inf` when dividing zero

---
## Designs Considerations

### Try ... Finally

ContextManager most commonly uses to abstract away `try...finally...` logics:

```python
my_obj = someClass()

try:
	my_obj.do_something_beginning()
	
	my_obj.do_something()
	do_other_things(my_obj.property)
	
except SomeAcceptableException as e: 
	my_obj.error_handling()
	
finally:
	# this is the part crucial
	my_obj.do_something_regardless()  
```

The key element in here is that, ContextManager ensures `finally...` logics **won't be left out by developers by mistakes and ensure that are executed regardless** by fully controlled using a ContextManager. 

```python
with someClass() as my_obj:
	my_obj.do_something()
	do_other_things(my_obj.property)
```

Using ContextManager, the code clean-up both [[#Error Handling Structure|Exception-handling]] & Finally-handling, and keeps only the core logics expose. 

---
## Basic Structure

Implementing ContextManager is mainly about creating the Entering and Exiting logics and hide it from dev-users. The basics structure of ContextManager can be represented by this flow:  

![[3_hidden/_images/Pasted image 20230503235602.png]]

- `with ...` starts - create an instance of class object, then immediately executes any logics at the beginning 
- inside the scope of `with ...` - executes the core logics (whether it is class's methods or other functions interact with the class object) 
- exiting `with...` - executes any exiting methods (e.g., closing files) 

```python
class MyClass:
	...

	def __enter__(self, *args, **kwargs):
		self.some_start_method()
		
		# this usually returns the class itself
		# but can also returns None
		return self  

	def __exit__(self, exc_type, exc_value, exc_tb):
		# methods that could exec in finally block
		self.finally_method()
		return True
```

---
## Error Handling Structure

Sometime errors would happen and it is consider as "acceptable" for our class within the Context, e.g., dividing zero, skip corrupted lines when reading files, etc. 

![[3_hidden/_images/Pasted image 20230504000507.png]]

- follows the same structure as before 
- `Exception` is raised within `with ...` execution - Context immediately ends and execute `__exit__` logics: 
	- optionally if there are any Exception-handling, then passes the error
	- optionally if there any unhandled Exception, then raises the error

```python
class MyClass:
	...

	def __enter__(self, *args, **kwargs):
		...
		return self  

	def __exit__(self, exc_type, exc_value, exc_tb):
		if exc_type is None: 
			self.happy_path_handling()
			return True

		# catch acceptable errors and handle it
		if exc_type is SomeAcceptableException:
			self.error_handling()
			self.finally_method()
			return True
		
		# unacceptable errors that can't be handled
		# should raises error and terminate
		return False
```

There are two key points in the `__exit__` in order to do error handling. The args that is required in `__exit__`, these are the details of the Exception that is being caught within the Context. 
- `exc_type` - the `Exception` class object, e.g., `ValueError`
- `exc_value` - usually the error messages along with the exception
- `exc_tb` - the traceback messages along with the exception

The return values of `__exit__` determines whether the Exception should be suppressed or not: 
- `return True` - Exception is suppressed, eqv to `pass`
- `return False` - Exception is raised, eqv to `raise`

### General Approach to Handle Error 

Generally, to handle error within the ContextManager: 
- modify object's state, e.g., error/ none/ default value when there're errors
- execute another methods as "fallback methods"
- additional closing tasks on top of exiting tasks, e.g., rolling back commits before closing connections when inserting erroneous values into database

---
## ‚ÑπÔ∏è¬† Resources
- [Context Managers and Python's with Statement ‚Äì Real Python](https://realpython.com/python-with-statement/)
- `python_archives/context_manager/`